// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

//This is Other Image Path reference demo
namespace XNativeiOS.Storyboards
{
	public partial class FirstViewController : UIViewController
	{
		public FirstViewController (IntPtr handle) : base (handle)
		{

		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			// Set image in code
			 MonkeyImage.Image = UIImage.FromFile ("Images/Red/RedMonkey.png");

			/* It should templated Image*/
			//MonkeyImage.Image = UIImage.FromBundle ("PurpleMonkey");
			//MonkeyImage.TintColor = UIColor.Yellow;
		}
	}
}
