// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XNativeiOS.Storyboards
{
	public partial class StackViewDemoView : UIViewController
	{
		public StackViewDemoView (IntPtr handle) : base (handle)
		{
		}
	}
}
